package com.fbfs.automatedunderwriting;

import com.fbfs.pc.au.model.declarativemodel.DM_CancellationTransaction;
import com.fbfs.pc.au.model.declarativemodel.DM_AutomatedUnderwritingUser;


rule "Agenda Group Cancel"

    agenda-group "control"
    salience 1002
	when
		DM_CancellationTransaction() and
		DM_AutomatedUnderwritingUser()
	then
		drools.setFocus("BR_Cancel");


end
