package com.fbfs.automatedunderwriting;

import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.ecd.model.PropertyLineOfBusiness;
import com.fbfs.pc.ecd.model.Policy; 
import com.fbfs.pc.ecd.model.UnderwritingQuestion;
import com.fbfs.pc.ecd.model.Dwelling;
import com.fbfs.pc.ecd.model.Coverage;
import java.lang.Number;

rule "BR__Property Liability Underwriting Question Needs Review New__UND(Change)~5165~"
	agenda-group "BR_Change"
	dialect "mvel"
	when
	PropertyLineOfBusiness( deleted != true )
	Policy( $underwritingQuestionList : underwritingQuestionList)
(
( Dwelling( deleted != true, occupancyStatus == "OO" )  and
 UnderwritingQuestion( lineOfBusiness == "PRPL" , answer == true, questionNum == "42", added == true || previousAnswer == false || (previousAnswerDetail != null && answerDetail != previousAnswerDetail)) from $underwritingQuestionList) 
  or 
 ( Dwelling(occupancyStatus == "OO", added == true || (previousOccupancyStatus != null && previousOccupancyStatus != "OO") )  and
 UnderwritingQuestion( lineOfBusiness == "PRPL" , answer == true, questionNum == "42") from $underwritingQuestionList) 
   or
(Coverage( coverageCode == "HPP" , added == true) and 
UnderwritingQuestion( lineOfBusiness == "PRPL" , questionNum == "13",  answer == true) from $underwritingQuestionList) 
 or
(Coverage( coverageCode == "HPP" , deleted != true) and 
UnderwritingQuestion( lineOfBusiness == "PRPL" , answer == true, questionNum == "13", added == true || previousAnswer == false || (previousAnswerDetail != null && answerDetail != previousAnswerDetail)) from $underwritingQuestionList) 
)
then
        WorkItemReason fact0 = new WorkItemReason();
        fact0.setType( "Policy" );
		fact0.setQueue( "Undw" );
		fact0.setReason( "5165: Property/liability underwriting question needs review (Change)." );
		fact0.setAddAction( "Review Question" );
		fact0.setAddAction( "FB Memo" );
		fact0.setAddLink( "Underwriting questions link" );
		fact0.setAddBookmark( "UnderwritingQuestions" );
	    fact0.setAddBookmarkUnit( "None" );
		fact0.setMgmtReportingCategory( "PLOB" );
		fact0.setMgmtReportingUnitAtRisk( "PLOB" );
		insert( fact0 );
end

