package com.fbfs.automatedunderwriting;

import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.ecd.model.PropertyLineOfBusiness;
import com.fbfs.pc.ecd.model.Policy;
import com.fbfs.pc.ecd.model.UnderwritingQuestion;
import com.fbfs.pc.ecd.model.Dwelling;
import java.lang.Number;

rule "BR__Property Liability Underwriting Question Needs Review New__UND(Change)~5165~"
	agenda-group "BR_Change"
	dialect "mvel"
	when
	PropertyLineOfBusiness( deleted != true )
	Policy( $underwritingQuestionList : underwritingQuestionList)
(	(UnderwritingQuestion( lineOfBusiness == "PRPL" , answer == true, questionNum != "1", questionNum != "4", questionNum != "11", added == true || previousAnswer == false || (previousAnswerDetail != null && answerDetail != previousAnswerDetail)) from $underwritingQuestionList) or 
(
			(UnderwritingQuestion( lineOfBusiness == "PRPL" , answer == false, questionNum == "11", added == true || previousAnswer == true || (previousAnswerDetail != null && answerDetail != previousAnswerDetail)) from $underwritingQuestionList)
               and
			   (Dwelling ( dwellingType == "MH", deleted != true ) )
)
)
then
        WorkItemReason fact0 = new WorkItemReason();
        fact0.setType( "Policy" );
		fact0.setQueue( "Undw" );
		fact0.setReason( "5165: Property/liability underwriting question needs review (Change)." );
		fact0.setAddAction( "Review Question" );
		fact0.setAddAction( "FB Memo" );
		fact0.setAddLink( "Underwriting questions link" );
		fact0.setAddBookmark( "UnderwritingQuestions" );
	    fact0.setAddBookmarkUnit( "None" );
		fact0.setMgmtReportingCategory( "PLOB" );
		fact0.setMgmtReportingUnitAtRisk( "PLOB" );
		insert( fact0 );
end