package com.fbfs.automatedunderwriting;

import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.ecd.model.Liability;
import com.fbfs.pc.ecd.model.Coverage;

rule "TestMadanDRL1"
                agenda-group "BR_Change"
                dialect "mvel"
                when
                                liability : Liability( unitAtRiskNumber : unitAtRiskNumber)
                                exists (                  Coverage( coverageCode == "BIPDH" , added == true ) from liability.coverageList
) 
                then
                                WorkItemReason fact0 = new WorkItemReason();
                                fact0.setType( "Policy" );
                                fact0.setQueue( "Undw" );
                                fact0.setReason( "5484:TestMadanDRL1" );
                                fact0.setAddAction( "General Review" );
                                fact0.setAddAction( "Review for farm/ranch income" );
                                fact0.setAddLink( "Liability link" );
                                fact0.setAddBookmark( "LB" );
                                fact0.setAddBookmarkUnit( unitAtRiskNumber );
                                fact0.setMgmtReportingCategory( "UAR" );
                                fact0.setMgmtReportingUnitAtRisk( unitAtRiskNumber );
                                insertLogical( fact0 );
end
