package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.ecd.model.Policy;
import com.fbfs.pc.ecd.model.Client;
import com.fbfs.pc.ecd.model.ClientRelationship;
import com.fbfs.pc.ecd.model.ClientName;


rule "TR__WorkItem Setup Client Name"

agenda-group "IT_WorkItem"
when
	workItem : WorkItem( )
        policy : Policy( )
	clientRelationship : ClientRelationship( deleted == false, type == "40") from policy.clientRelationshipList
	client : Client ( clientReference == clientRelationship.clientReference ) from policy.clientList
	clientName : ClientName ( ) from client.nameList
then
     	workItem.setInsFirstName( clientName.getFirstName() );
	workItem.setInsLastName( clientName.getLastName() );


end
