package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.declarativemodel.DM_NewBusinessTransaction;
import com.fbfs.pc.au.model.declarativemodel.DM_TaskType;



rule "TR__WorkItem Task Type CREATE_FILE New Business 2"

agenda-group "IT_WorkItem"
when
	  DM_NewBusinessTransaction()
   not(DM_TaskType())
	//not (exists(workItemReason : WorkItemReason( type == "Policy", reason != null)))
	//DM_CurrentTransaction (effectiveDate : effectiveDate ) 
	//eval(calculateDaysBetween(effectiveDate, new Date()) > 39)
	workItem : WorkItem( type == "Policy" )
	
then
	workItem.setTaskType("CREATE_FILE");
        DM_TaskType taskType = new DM_TaskType("CREATE_FILE");
	insert(taskType);



end
