package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.declarativemodel.DM_FarmRanchLiabilityCoverage;
import com.fbfs.pc.au.model.declarativemodel.DM_ChangeTransaction;




rule "TR__WorkItem Routing Policy Non Farm Asst Underwriting"

agenda-group "IT_FinalRules"
when
	not (exists(DM_FarmRanchLiabilityCoverage()))
	workItem : WorkItem( type == "Policy" )
	WorkItemReason( type == "Policy", queue == "Asst Undw Farm" || == "Asst Undw" )
	not (exists(WorkItemReason( type == "Policy", owner != null )))
	not (exists(WorkItemReason( type == "Policy", queue == "Undw" )))
	not (exists(WorkItemReason( type == "Policy", queue == "Undw Farm" )))	
	//not (exists(Policy ( state == 'AZ' ) and DM_ChangeTransaction()))
then
	workItem.setQueue("Asst Undw");

end
