rule 'TR__Definition Tenant Only Policy'
dialect 'mvel'
agenda-group "IT_Rules"
when
	
coverage : Coverage() 
 
 
 
   cntDwell : Number(intValue >= 0) from accumulate ( dwelling : Dwelling(dwellingType == "H1"  || == "H2" || == "H3" || == "H4" || == "M1"  || == "M2" || == "M3" || == "M4" , status == "A" || == "P" ) and
  dwlCov : Coverage() from dwelling.coverageList, count(dwlCov)) 

 cntSpp : Number(intValue >= 0) from accumulate ( spp : ScheduledPersonalProperty( ) and
sppCov : Coverage() from spp.coverageList, count(sppCov)) 
  
   cntLiab : Number(intValue >= 0) from accumulate ( liab : Liability( ) and
  liabCov : Coverage() from liab.coverageList, count(liabCov)) 
  
  cntLob : Number(intValue >= 0) from accumulate ( lob : PropertyLineOfBusiness( ) and
  lobCov : Coverage() from lob.coverageList, count(lobCov))  
  
  cntAllCov : Number(intValue >= 0 ) from accumulate ( coverage1 : Coverage(), count(coverage1) )



 eval((cntDwell +  cntSpp + cntLiab) >= (cntAllCov - cntLob )  ) 
 
not (exists(VehicleLineOfBusiness( ))) 
not (exists(LineOfBusiness(lineOfBusiness  == "UMB")))
not (exists  ( location : Location( locationNumber : locationNumber) and
		 LocationSupplement( locationUse == "S" || locationUse == "F"  ) from location.supplement ))
 
 
 
	then
		DM_TenantOnlyPolicy top = new DM_TenantOnlyPolicy();
	insert(top);



end
