package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.declarativemodel.DM_FarmRanchLiabilityCoverage;
import com.fbfs.pc.au.model.declarativemodel.DM_ChangeTransaction;
import com.fbfs.pc.au.model.declarativemodel.DM_CurrentTransaction;



rule "TR__WorkItem Task Type Non Farm PMP_CHANGE"

agenda-group "IT_WorkItem"
when
	not (exists(DM_FarmRanchLiabilityCoverage()))	
	workItem : WorkItem( type == "Policy")
	DM_ChangeTransaction()
	policy : Policy( currentTerm : currentTerm )
	DM_CurrentTransaction( eval(convertToDouble(termIdent) >= convertToDouble(currentTerm)) )
	(exists(workItemReason : WorkItemReason( type == "Policy", reason != null )))  	
then
	workItem.setTaskType("PMP_CHANGE");
DM_TaskType taskType = new DM_TaskType("PMP_CHANGE");
	insert(taskType);

end
