package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.workitem.WorkItem;


rule "TR__Workitem Priority Medium - Policy WI"

agenda-group "IT_FinalRules"
when
	workItem : WorkItem( type == "Policy" )		
	(exists(WorkItemReason( type == "Policy", priority == "Medium" )))	
        not(exists(WorkItemReason( type == "Policy", priority == "High" )))	
then
	workItem.setPriority("Medium");

end
