package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.declarativemodel.DM_FarmRanchLiabilityCoverage;
import com.fbfs.pc.au.model.declarativemodel.DM_NewBusinessTransaction;



rule "TR__WorkItem Task Type Farm PMP_F_NB"

agenda-group "IT_WorkItem"
when
	DM_FarmRanchLiabilityCoverage()
	workItem : WorkItem( type == "Policy")
	DM_NewBusinessTransaction()
	(exists(workItemReason : WorkItemReason( type == "Policy", reason != null )))


then
	workItem.setTaskType("PMP_F_NB");
	DM_TaskType taskType = new DM_TaskType("PMP_F_NB");
	insert(taskType);

end
