package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.workitem.WorkItemPendReason;
import com.fbfs.pc.au.model.declarativemodel.DM_RewriteTransaction;


rule "TR__WorkItem Task Type CREATE_FILE Rewrite 3"

agenda-group "IT_WorkItem"
when
	DM_RewriteTransaction()
	not (exists(workItemReason : WorkItemReason( workItemReasonType : type == "Policy", reason != null )))
	not (exists(workItemPendReason : WorkItemPendReason (type == "Policy")))
	workItem : WorkItem( type == "Policy" )
then
	workItem.setTaskType("CREATE_FILE");
        DM_TaskType taskType = new DM_TaskType("CREATE_FILE");
	insert(taskType);


end
