package com.fbfs.automatedunderwriting;
import com.fbfs.pc.au.model.workitem.WorkItemReason;
import com.fbfs.pc.au.model.workitem.WorkItem;
import com.fbfs.pc.au.model.declarativemodel.DM_FarmRanchLiabilityCoverage;
import com.fbfs.pc.au.model.declarativemodel.DM_NewBusinessTransaction;



rule "TR__WorkItem Routing Policy Farm  New Business"

agenda-group "IT_FinalRules"
when
	DM_FarmRanchLiabilityCoverage()
	DM_NewBusinessTransaction()
	workItem : WorkItem( type == "Policy" )	
	not (exists(WorkItemReason( type == "Policy", owner != null )))
then
	workItem.setQueue("Undw Field");



end
